name: test

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Build nxf (runs go test via buildGoModule)
        run: nix build --print-build-logs
      - name: Flake check
        run: nix flake check --print-build-logs
